### ISSUE TITLE
Use of touchAction: none

### ISSUE THREAD

**Issue by benmerckx** [cmswalker/scroll-swipe#3]
While creating a touch slider (whith horizontal swiping to advance) I noticed the element did not allow the native vertical scroll behaviour. I disabled `touchPreventDefault` in the settings but that didn't help. Anyway, I found the [`style.touchAction = 'none'`](https://github.com/cmswalker/scroll-swipe/blob/master/lib/ScrollSwipe.js#L61) really just disables any native browser events to be triggered, which renders `touchPreventDefault: false` a bit useless.

**Comment by cmswalker** [comment]
Hi @benmerckx 

Yes this intentionally blocks all events until you free them up or delegate them.  Could you show me your setup?  

The example is the easiest way to get started because it instantly calls `listen()` to open the DOM back up for events. In a real-world scenario you'd likely animate or change some state or something before calling `listen()` again.  I chose to block triggered events vs using `style.touchAction = 'none'` because of cross-compatibility https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action  (Safari likes to play with fire to give iOS users a different experience)

Let me know, as `touchPreventDefault` should be locking down scroll until the client decides what to do with it and this could be a bug

**Comment by benmerckx** [comment]
The issue I'm having is not with the default behaviour, which I think is fine. My setup is an image slider in the middle of the page which the user may navigate horizontally. The problem is trying to reach the content below is then impossible as you can't continue scrolling vertically, because that is blocked by the css rule (which is set regardless of the `touchPreventDefault` option value): https://github.com/cmswalker/scroll-swipe/blob/master/lib/ScrollSwipe.js#L61

I might be wrong here but I think having both `preventDefault` and `touchAction: none` is  counterintuitive as `touchAction` already effectively blocks everything. Which starts the confusion as it renders `touchPrevenDefault: false` useless. I'd suggest taking out the style rule which would make this behave as expected.

I'm not sure this properly explains the problem, if not I'll set up a jsfiddle to demonstrate.

**Comment by benmerckx** [comment]
Looking at your response again I have the feeling this line was left in unintentionally:
https://github.com/cmswalker/scroll-swipe/blob/master/lib/ScrollSwipe.js#L61

**Comment by cmswalker** [comment]
Ah yes, I dont think that was intentional. What happens when you remove it locally in your node_modules folder?

Also, what are you using for your target in the ScrollSwipe options?  It doesn't have to be document.body as is in the example, the dom node your slider is wrapped in should work.

**Comment by benmerckx** [comment]
I'm using a div element as target. Once I noticed the style rule on there, I used `touch-action: initial !important;` to overwrite it in css (which makes `touchPreventDefault` work as expected). Then reported the issue as I think others might run in to it as well.

**Comment by cmswalker** [comment]
Ah great, I have removed the bunk line. Thanks for finding!

You can now update to v 0.0.10
